"""initial

Revision ID: aaa4a27f5e8e
Revises: 
Create Date: 2025-08-29 18:26:59.268004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa4a27f5e8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CLIENTE',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_razon_social', sa.String(length=255), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('ubicacion_general', sa.Text(), nullable=True),
    sa.Column('saldo_total_pagado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('saldo_total_pendiente', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('PROPIEDAD',
    sa.Column('id_propiedad', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('finca', sa.String(length=100), nullable=True),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.Column('padron', sa.String(length=100), nullable=True),
    sa.Column('superficie_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('coordenadas', sa.String(length=255), nullable=True),
    sa.Column('mapa_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTE.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_propiedad')
    )
    op.create_table('PROYECTO',
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('anho', sa.Integer(), nullable=True),
    sa.Column('institucion', sa.String(length=100), nullable=True),
    sa.Column('tipo_tramite', sa.String(length=100), nullable=True),
    sa.Column('fecha_firma_contrato', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('plazo_limite', sa.Date(), nullable=True),
    sa.Column('id_propiedad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTE.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_propiedad'], ['PROPIEDAD.id_propiedad'], ),
    sa.PrimaryKeyConstraint('id_proyecto')
    )
    op.create_table('VENCIMIENTO',
    sa.Column('id_vencimiento', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('id_propiedad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTE.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_propiedad'], ['PROPIEDAD.id_propiedad'], ),
    sa.PrimaryKeyConstraint('id_vencimiento')
    )
    op.create_table('DOCUMENTO_PROYECTO',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('archivo_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['PROYECTO.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('FACTURA',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('comprobado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['PROYECTO.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_table('NOTIFICACION',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_vencimiento', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_vencimiento'], ['VENCIMIENTO.id_vencimiento'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('PAGO',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('porcentaje_pago_inicial', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('saldo_restante', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['PROYECTO.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PAGO')
    op.drop_table('NOTIFICACION')
    op.drop_table('FACTURA')
    op.drop_table('DOCUMENTO_PROYECTO')
    op.drop_table('VENCIMIENTO')
    op.drop_table('PROYECTO')
    op.drop_table('PROPIEDAD')
    op.drop_table('CLIENTE')
    # ### end Alembic commands ###
